title: mathis-durand        
email: me@mathis-durand.fr  
description: >-         
  This is my professional website showcasing my projects and skills.

baseurl:           
url: "https://mathis-durand.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
#remote_theme: pages-themes/architect@v0.2.0

# Plugins
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude files/folders from being processed
exclude:
  - Gemfile
  - README.md

# Collections
collections:
  projects:
    output: true        # Generate pages for each project
    permalink: /projects/:path/
  publications:
    output: true      # Generate HTML files
    permalink: /publications/:path/  # Optional: Customize URLs
