title: mathis-durand        
email: me@mathis-durand.fr  
description: >-         
  This is my professional website showcasing my projects and skills.

baseurl:           
url: "https://mathis-durand.github.io"

# Build settings
markdown: kramdown
remote_theme: pages-themes/architect@v0.2.0

# Plugins 
plugins:
  - jekyll-remote-theme

# Exclude files/folders from being processed
exclude:
  - Gemfile
  - README.md

# Collections
collections:
  projects:
    output: true        # Generate pages for each project
    permalink: /projects/:path/
